global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: discord
    webhook_configs:
      - url: "discord_url..."
        send_resolved: true

  - name: slack
    webhook_configs:
      - url: "slack_url..."
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
