global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
      timeout: 10s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090

  - job_name: master
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: client1.local
    static_configs:
      - targets:
        - '192.168.56.3:9100'

  - job_name: client2.local
    static_configs:
      - targets:
        - '192.168.56.4:9100'
