networks:
  monitoring:
    driver: bridge

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - alertmanager_data:/alertmanager
      - "./alertmanager_conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
      - "--web.listen-address=:9093"
    expose:
      - 9093
    networks:
      - monitoring
    depends_on:
      - node-exporter

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./prometheus_conf:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
    # ports:
    #   - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
      - "./grafana_conf/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana_conf/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
    networks:
      - monitoring

volumes:
  grafana_data: {}
  grafana_logs: {}
  prometheus_data: {}
  alertmanager_data: {}
